### ISSUE TITLE
Parameter "max pose detections" does not work

### ISSUE THREAD

**Issue by maweibezahn** [oveddan/posenet-for-installations#12]
I want to use single pose detection, but setting this parameter to "1" (or even "0") in the UI has no effect – see attached image.
![maxposedetections](https://user-images.githubusercontent.com/2930440/50351056-49c26300-0541-11e9-829e-af5b145ea6ec.jpg)

**Comment by oveddan** [comment]
@maweibezahn this has been fixed.
