### ISSUE TITLE
GCS URL of posenet model seems to be empty

### ISSUE THREAD

**Issue by glaforge** [oveddan/posenet-for-installations#13]
https://github.com/oveddan/posenet-for-installations/blob/39a0d5c83854709c9fa040ca2e01a52665395ba6/client/downloadModels.js#L85

Accessing this location yields:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: tfjs-models/weights/posenet/</Details>
</Error>
```

Has the posenet model moved somewhere else?

**Comment by syborg91** [comment]
This https://storage.googleapis.com/tfjs-models/ yields an XML with lots of metadata about the models (including the new resnet50). Not quite sure how to access the pretrained models themselves.

**Comment by oveddan** [comment]
Thanks for letting me know about this.  I'm working on upgrading to posenet 2.0 and that will resolve this.
See #14
